previews:
  generation: automatic

services:
  # ===============================================
  # 1️⃣  Main FastAPI Backend
  # ===============================================
  - type: web
    name: mpita-medical-api
    runtime: python
    repo: https://github.com/Louizyyye/mpitadevv
    branch: main
    plan: starter
    region: frankfurt

    # Build and run FastAPI
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000

    autoDeployTrigger: 'on'

    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mpita-medical-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: DEBUG
        value: "False"
      - fromGroup: mpita-env

    healthCheckPath: /docs

    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 70
      targetMemoryPercent: 70

  # ===============================================
  # 2️⃣  Background Notification Worker
  # ===============================================
  - type: worker
    name: mpita-notification-worker
    runtime: python
    repo: https://github.com/Louizyyye/mpitadevv
    branch: main
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python app/workers/notifications.py
    envVars:
      - fromGroup: mpita-env
      - key: DATABASE_URL
        fromDatabase:
          name: mpita-medical-db
          property: connectionString

  # ===============================================
  # 3️⃣  Cron Job — Database Auto Backup
  # ===============================================
  - type: cron
    name: mpita-db-backup
    runtime: python
    schedule: '0 0 * * *'  # daily at midnight
    repo: https://github.com/Louizyyye/mpitadevv
    buildCommand: pip install -r requirements.txt
    startCommand: python app/scripts/backup.py
    envVars:
      - fromGroup: mpita-env
      - key: DATABASE_URL
        fromDatabase:
          name: mpita-medical-db
          property: connectionString

  # ===============================================
  # 4️⃣  Static Frontend / Docs Site (Optional)
  # ===============================================
  - type: web
    name: mpita-medical-docs
    runtime: static
    repo: https://github.com/Louizyyye/mpitadevv
    branch: main
    buildCommand: python generate_docs.py
    staticPublishPath: ./public
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: redirect
        source: /
        destination: /docs

# ===============================================
# 🗄️ DATABASES (MYSQL)
# ===============================================
databases:
  - name: mpita-medical-db
    plan: standard
    databaseName: mpita_medical
    user: mpita_admin
    ipAllowList:
      - source: 0.0.0.0/0
        description: open-access-for-render
    diskSizeGB: 10
    highAvailability:
      enabled: false

# ===============================================
# 🔐 ENVIRONMENT GROUP
# ===============================================
envVarGroups:
  - name: mpita-env
    envVars:
      - key: APP_NAME
        value: Mpita Medical System
      - key: EMAIL_SENDER
        value: no-reply@mpitahealth.com
      - key: LOG_LEVEL
        value: info
      - key: TIMEZONE
        value: Africa/Nairobi
      - key: MAX_CONNECTIONS
        value: "20"
      - key: REDIS_URL
        value: redis://default:password@localhost:6379/0
      - key: ENABLE_NOTIFICATIONS
        value: "true"
